### ISSUE TITLE
Format / compile HEEx files

### ISSUE THREAD

**Issue by Sleepful** [lexical-lsp/lexical#100]
Currently HEEx files have zero support.

Being capable of using `format` would be a good starting point, it is a basic operation that requires zero code intelligence.

Currently `mix format` supports formatting HEEx files through a plug-in: 
- https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.HTMLFormatter.html
- https://hexdocs.pm/mix/main/Mix.Tasks.Format.html#module-plugins

Can it be easily integrated into lexical?

**Comment by scottming** [comment]
I think you can refer to this implementation: https://github.com/hrzndhrn/recode/pull/46/files#diff-98f3688a2e1d9601d98c77d9cc37e1871af489e7ec8f076526e9be56b99c4db2R50

**Comment by scohen** [comment]
This came up in the elixir chat today. I think what's required to handle these files is:

  1. Rename `Lexical.RemoteControl.Build.File` to `Lexical.RemoteControl.Build.Document` and the file to `document.ex`
  2. Detect the file path prior to compile, if it has `heex` or `eex` in it, delegate to a different compile function that handles that type. 
  3. I think that is all.

Formatting should work, since `heex` and `eex` have `mix format` plugins.

**Comment by scottming** [comment]
Fixed by #323
