### ISSUE TITLE
Potential issue with beam process name collisions

### ISSUE THREAD

**Issue by megalithic** [lexical-lsp/lexical#291]
I'm presently working on a couple of different elixir apps and have them connected via `--sname`. The `sname` values i'm using for my two apps are their actual app_names. This is also what lexical seems to use. So I ended up getting the following error to my lsp logging (using nvim at `master`):

```
[ERROR][2023-07-27 11:12:22] .../vim/lsp/rpc.lua:676	"rpc"	"/Users/me/.local/share/lsp/lexical/_build/dev/rel/lexical/start_lexical.sh"	"stderr"	"Protocol 'inet_tcp': the name retriever@127.0.0.1 seems to be in use by another Erlang node\r\n"

```

It tends to stop working from this point, and it doesn't show as being connected any longer to the buffer.

I'm using lexical at commit 8b084d1596c21aa3eac21c973975c24997079f2a

**Comment by scohen** [comment]
@megalithic that's interesting; lexical uses long names for its nodes. I had no idea that they'd conflict with short names.

The fix is relatively simple (just make the name of the node something like `lexical-<project-name>-<manager-randomness>@127.0.0.1`), we're tracking it in #91, but this wasn't a problem for us, as we don't run distribution locally. 

I can put together a PR pretty quickly that would fix this.

**Comment by megalithic** [comment]
Thanks for the quick response @scohen. That'd be fantastic!

**Comment by scohen** [comment]
@megalithic check out #294

**Comment by megalithic** [comment]
:hero: thanks @scohen
