### ISSUE TITLE
Lexical LS with Zed editor

### ISSUE THREAD

**Issue by drumusician** [lexical-lsp/lexical#313]
I would love to give Lexical a try, but my editor of choice these days is [Zed editor](https://zed.dev/) 

From the episode of Thinking Elixir I understood that lexical can be configured by overriding the path to elixir-ls, just not sure how to go about doing that.

Is there anyone that has done this? If not I'll switch to VSCode for the time being to try it out.

Maybe [@aexvir](https://github.com/aexvir) or [@iamnbutler](https://github.com/iamnbutler) from Zed are able to help out here maybe?

**Comment by scohen** [comment]
@drumusician I looked at the zed docs, and I don't see anywhere that you can override the path to elixir-ls's executable. 

There is an [open zed community issue here](https://github.com/zed-industries/community/issues/1567), but as a closed source project, all we can do is ask them. That's too bad, because lexical is compatible with elixir-ls, and all they'd have to do is expose a configuration item for the path. 

I saw there as was a mention of lexical in a similar thread asking to support an additional LS for ruby, but the objections from the zed team aren't valid for lexical.

**Comment by scohen** [comment]
@drumusician one trick you could do is link the `language_server.sh` that brew installs file to `start_lexical.sh`

**Comment by scohen** [comment]
Closing this issue, as there's nothing I can do about it.

**Comment by reisub** [comment]
For anyone interested in making this happen, please upvote https://github.com/zed-industries/community/issues/1968.

**Comment by mikayla-maki** [comment]
Hey y'all, we don't fully support Lexical yet but there's some instructions here for integrating Lexical into Zed :) https://github.com/zed-industries/community/issues/1567#issuecomment-1741599389
