### ISSUE TITLE
running 'mix package' did not create a proper package

### ISSUE THREAD

**Issue by mavuio** [lexical-lsp/lexical#341]
FYI:

I had issues running the 'mix package' task:

The task did not create the 'lx_*.ez' files in the package's 'lib/' directory
only the non-prefixed ones were created.

I solved that by symlinking all directories to a version with an 'lx_' prefix  in the '_build/dev/lib/'  dir
after running 'mix compile' before running 'mix package' 

I'm running OTP-26.0.2 via asdf on an M1 MacBook

**Comment by scottming** [comment]
Did you try this pr: #332 , or remove the `_build` before running `mix package` or use `otp-25.3.2, elixir 1.14.5` to `mix package`?

@mavuio

**Comment by scohen** [comment]
@mavuio can you provide reproduction steps, and the version of elixir you're using?

**Comment by scohen** [comment]
You shouldn't have to do any symlinking, and which directories had the `lx_*.ez` files in it?

**Comment by ryoung786** [comment]
I was able to reproduce this -- turns out I had cloned lexical into my `~/dev/language_servers/elixir/` directory, and the namespacing tasks was replacing that with `~/dev/language_lx_servers/elixir/`.

Cloning into `~/dev/foo/elixir/` fixes the issue -- I'd recommend that as a workaround until they can push a fix.

Thanks to @scohen for pair-debugging the above w/me!

**Comment by scohen** [comment]
@mavuio What is the path to your lexical checkout?
Do any of the parent directories contain the following words: "common", "server", "remote_control", "proto" ?
