### ISSUE TITLE
Go To Definition and Hover do not work in a Phoenix generated controller

### ISSUE THREAD

**Issue by rverton** [lexical-lsp/lexical#384]
Hi,
I'm playing with lexical-ls and noticed that some LSP actions do not work in a Phoenix generated file.

Versions:
- Erlang/OTP 25 [erts-13.2.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
- Elixir 1.14.5 (compiled with Erlang/OTP 24)
- {:phoenix, "~> 1.7.7"}
- lexical-ls, commit eeef7ea5ab149b3b530238fb71dba5f5f8d06f59, neovim

To reproduce:
`mix phx.new demo`

There is a file generated under `lib/demo_web/controllers/page_controller.ex':
```elixir
defmodule DemoWeb.PageController do
  use DemoWeb, :controller

  def home(conn, _params) do
    # The home page is often custom made,
    # so skip the default app layout.
    render(conn, :home, layout: false)
  end
end
```

Doing a 'Go To Definition' or 'Hover' when the cursor is on `render` does nothing. Just for comparison: In elixir-ls, both work.

**Comment by scohen** [comment]
Lukasz pinged me, and this is a long standing issue in elixir_sense that arises from it not being compiled in the version of elixir that you're running. 
the good news is the immediate fix is to build lexical yourself, which is why I couldn't replicate. Other good news is that our upcoming indexer doesn't suffer this problem. 

Since it's old, has a workaround, and we're moving off that technology, I'm not going to fix.

**Comment by rverton** [comment]
All right, thanks for the info! Looking forward to the indexer. Just a little note to add: I did compile it by myself in this case.
