### ISSUE TITLE
Env variables being logged to lexical.log

### ISSUE THREAD

**Issue by wkirschbaum** [lexical-lsp/lexical#488]
I see the crash reports in lexical.log outputs environment variables. This is not safe as it might reveal the environment when sharing crash reports creates potential sensitive artifacts in projects ( which might accidentally be pushed to git ).

an example: 
```bash
** (exit) an exception was raised:
    ** (ErlangError) Erlang error: :eacces:

  * 1st argument: invalid port name

        (erts 14.1.1) :erlang.open_port({:spawn_executable, "/home/wilhelm/.config/emacs/.cache/lsp/lexical/lexical/priv/port_wrapper.sh"}, [env: [{~c"XDG 
 ```

**Comment by wkirschbaum** [comment]
I think a solution might be to whitelist the ENV variables rather than preventing logging, which is probably safer and simpler.

**Comment by scohen** [comment]
(catching github up with our slack conversation)

We can't whitelist variables because the variables aren't for lexical, they're for `asdf` and `rtx` and i think making lexical cognizant of which variables are required for each version manager will make lexical buggy.

Given that the attack surface is a user pasting their variables onto some website, which is pretty small, I'm going to close this as wontfix, but thank you for reporting it.
