### ISSUE TITLE
While find/replacing in VSCode across many files formatting save takes a long time and bungles replace.

### ISSUE THREAD

**Issue by krainboltgreene** [lexical-lsp/lexical#815]
I did a search/replace in VSCode for "Core" to "Dashboard" across many files (200~) and VSCode hangs while letting Lexical format it. This also seems to result in future search/replace issues as a replace of `Core.AccountAuth` to `Dashboard.AccountAuth` turns `Core.AccountAuth, :ensure_authenticated` into `Dashboard.AccountAuthure_authenticated`. While the below screenshot shows them being saved each "save" takes ~3s and actually finishes (it's not locked up). That said the file is already saved, regardless of what the indicator says.

![Screenshot 2024-08-13 at 10 18 30 AM](https://github.com/user-attachments/assets/48fb5583-d1f4-47bb-82c7-cb025cb89b50)

Metadata:

```
Version: 1.92.1 (Universal)
Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
Date: 2024-08-07T20:16:39.455Z (5 days ago)
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 22.6.0
Lexical Extension: lexical-lsp.lexical v0.0.18
Erlang/OTP 27 [erts-15.0] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]
Elixir 1.17.1 (compiled with Erlang/OTP 27)
```

**Comment by scohen** [comment]
I've been able to replicate this, going to play around with this a bit and see if I can make this perform better.

**Comment by crbelaus** [comment]
This happens to me frequently as well. I have the format on save setting enabled and Lexical seems to be formatting the file and rebuilding the application for each saved file.

I wonder if it would make sense to have some kind of "debounce" to delay the application rebuild for a few milliseconds after saving a file. This way it would be triggered only after saving all the files instead of once for every file.

**Comment by scohen** [comment]
The build presently already has a debounce, but format doesn't. 
Things get a little tricky with debounces, because format requests expect a response within some amount of time, and they operate on an unsaved document. Thus, if you miss that window, there's no way that I know of to actually format the document.

**Comment by scohen** [comment]
@krainboltgreene @crbelaus can you check out the branch in #826, and see if that helps?

**Comment by krainboltgreene** [comment]
Will do.

**Comment by krainboltgreene** [comment]
Queuing this up for tonight, sorry was super busy yesterday.

**Comment by Moosieus** [comment]
I gave this a quick spot-check on main since #826 was merged, and it seems like this issue's resolved.

If someone may verify, I'll mark this issue as completed.

**Comment by scohen** [comment]
@krainboltgreene Can you verify?

**Comment by krainboltgreene** [comment]
It's very simple to test, I will do so in 14h when I start work again.

**Comment by krainboltgreene** [comment]
@scohen So search/replace is pretty slow now, but it seems like it's no longer lossy!

It's extremely unfortunate that VSCode doesn't plan on supporting a batch change message.

**Comment by krainboltgreene** [comment]
Oh by slow I mean that changing 23 files took about 5m on a very fast machine. Each file that had a replacement needed it's own compile.

**Comment by scohen** [comment]
@krainboltgreene can you check out my `performance` branch and try it again?
